version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./code/server/docker/initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build: ./code/server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/todo
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET=superVeryLongSecretKeyThatIsAtLeast32CharactersLong
    ports:
      - "5001:5001"

  client:
    build: ./code/client
    ports:
      - "9000:80"
    depends_on:
      - server

volumes:
  db-data:
